
# Name your package! Package names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'kdbt_template'
version: '0.0.1'

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'revzilla'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["screens","audits","staging_quality","production","partials"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

on-run-end:
  - >
    {% for schema_suffix in ["QUALITY", "STAGING_QUALITY", "GENERAL"] %}
      {% for snowflake_role in ["GENERAL_USER", "DEVELOPER"] %}
      GRANT USAGE ON SCHEMA {% if target.database == var('production_database') %} QUALITY {% else %} {{target.schema+'_'+schema_suffix}} {% endif %} TO ROLE {{snowflake_role}};
      GRANT SELECT ON ALL TABLES IN SCHEMA {% if target.database == var('production_database') %} QUALITY {% else %} {{target.schema+'_'+schema_suffix}} {% endif %} TO ROLE {{snowflake_role}};
      GRANT SELECT ON ALL VIEWS IN SCHEMA {% if target.database == var('production_database') %} QUALITY {% else %} {{target.schema+'_'+schema_suffix}} {% endif %} TO ROLE {{snowflake_role}};
      {% endfor %}
    {% endfor %}

models:
  revzilla:

  vars:
    release: "Harvey Mushman"
    app_version: 0.0.12
    dbt_version: 0.10.2
    production_database: 'DW2'

    partials:
      materialized: ephemeral

    audits:
      materialized: incremental
      sql_where: "TRUE"         ## This is legacy dbt that tells the framework to use the logic in the model.

    screens:
      materialized: incremental
      sql_where: "TRUE"

seeds:
  revzilla:
    enabled: true
    schema: SEED
    post-hook:
      - 'GRANT USAGE ON SCHEMA "RAW"."SEED" TO ROLE DEVELOPER'
      - 'GRANT USAGE ON SCHEMA "RAW"."SEED" TO ROLE DW2_ADMIN'
      - 'GRANT SELECT ON ALL TABLES IN SCHEMA "RAW"."SEED" TO ROLE DEVELOPER'
      - 'GRANT SELECT ON ALL TABLES IN SCHEMA "RAW"."SEED" TO ROLE DW2_ADMIN'    

      # configure each seed explicitly
    state_region_records:
      column_types:
        state: varchar(16777216)
        region: varchar(16777216)

    budget_plan_records:
      column_types:
        date: date
        revzilla_plan: number(38,0)
        cycle_gear_plan: number(38,0)
        upshift_plan: number(38,0)

    kenshoo_channel_mapping_records:
      column_types:
        site_name: varchar(16777216)
        marketing_channel_name: varchar(16777216)
        kenshoo_profile_name: varchar(16777216)
        kenshoo_channel_name: varchar(16777216)

    marketing_forecast_budget_records:
      column_types:
        site_name: varchar(16777216)
        year: number(38,0)
        week: number(38,0)
        total_site_revenue: float
        total_spend: float
        total_marketing_revenue: float
        seo_revenue: float
        paid_search_revenue: float
        paid_search_spend: float
        cse_revenue: float
        cse_spend: float
        display_retargeting_revenue: float
        display_retargeting_spend: float
        email_revenue: float
        affiliate_revenue: float
        affiliate_spend: float
        display_video_revenue: float
        display_video_spend: float
        social_revenue: float
        social_spend: float
        direct_revenue: float
        referral_revenue: float
        offline_revenue: float
        budget_released_at: timestamp_ntz(9)

    organizational_definition_records:
      column_types:
        term: varchar(16777216)
        definition: varchar(16777216)
        updated_at: date

    approved_abbreviation_records:
      column_types:
        abbreviation: varchar(16777216)
        full_term: varchar(16777216)
        reason_for_abbreviation: varchar(16777216)
